version: '3.8'
services:
  vueapp:
    build: .
    ports:
      - '80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.vueapp.rule=Host(`catapp.localhost`)'
      - "traefik.http.routers.vueapp.entrypoints=web"
      - "traefik.http.routers.vueapp.service=vueapp"
      - "traefik.http.services.vueapp.loadbalancer.server.port=80"
    depends_on:
      - traefik
    networks:
      - web
networks:
  web:
    external: true
