version: '3.8'
services:
  website-app:
    container_name: website
    build:
      context: .
      dockerfile: docker-images/Dockerfile
    ports:
      - '3000'
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.website-app.rule=Host(`julian-husson.com`)'
      - "traefik.http.routers.website-app.entrypoints=web"
      - "traefik.http.routers.website-app.service=website-app"
      - "traefik.http.services.website-app.loadbalancer.server.port=3000"
    networks:
      - web
networks:
  web:
    external: true
