version: '3.8'
services:
  website-app-dev:
    container_name: website-app-dev
    build:
      context: .
      dockerfile: docker-images/Dockerfile.dev
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
