version: '3.8'
services:
  website:
    container_name: website
    build:
      context: .
      dockerfile: docker-images/Dockerfile
    ports:
      - '3000'
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      #Routers
      - "traefik.http.routers.website.rule=Host(`julian-husson.com`)"
      - "traefik.http.routers.website.entrypoints=websecure"
      - "traefik.http.routers.website.tls.certresolver=resolver"
      - "traefik.http.routers.website.middlewares=rate-limit"
      #Services
      - "traefik.http.services.website.loadbalancer.server.port=3000"
      #Middlewares
      - "traefik.http.middlewares.rate-limit.ratelimit.average=5"
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=10"
    networks:
      - web
networks:
  web:
    external: true
